```{r}
## Minnow summary box plots 
# Colors for each group
A = "#e0db8b"
G= "#9bcce8"
M="#afd197"
L= "#cf8080"
color_groups= c(A,M,L,A,L,gl,gl,gl,A,gl,gl,L,L,gl,M,L,gl)
dist_groups=c("A","M","L","A","L","gl","gl","gl","A","gl","gl","L","L","gl","M","L","gl")
```
```{r}
# Glacial Relicts
g= gl+beg
gl_list=vector()
for(i in g){
  add = (which(lakes[,i]>=1))
  gl_list=list.append(gl_list,add)
}
gl_list=unique(gl_list)

# Sensitive Minnows
s=se+beg
se_list=vector()
for(i in s){
  add = (which(lakes[,i]>=1))
  se_list=list.append(se_list,add)
}
se_list=unique(se_list)


## Atlantic Minnows
a=at+beg
at_list=vector()
for(i in a){
  add = (which(lakes[,i]>=1))
  at_list=list.append(at_list,add)
}
at_list=unique(at_list)

#Mississippian Minnos
m=ms+beg
ms_list=vector()
for(i in m){
  add = (which(lakes[,i]>=1))
  ms_list=list.append(ms_list,add)
}
ms_list=unique(ms_list)


# All Minnows
m=minnows+beg
minnow_list=vector()
for(i in m){
  add = (which(lakes[,i]>=1))
  minnow_list=list.append(minnow_list,add)
}
minnow_list=unique(minnow_list)

# Lowland Minnows
l=lw+beg
lw_list=vector()
for(i in l){
  add = (which(lakes[,i]>=1))
  lw_list=list.append(lw_list,add)
}
lw_list=unique(lw_list)

### Metrics
gl_ph=lakes$LAB_PH[gl_list]
at_ph=lakes$LAB_PH[at_list]
ms_ph=lakes$LAB_PH[ms_list]
lw_ph=lakes$LAB_PH[lw_list]
minnow_ph=lakes$LAB_PH[minnow_list]

gl_elev=lakes$Volume.m3.[gl_list]
at_elev=lakes$Volume.m3.[at_list]
ms_elev=lakes$Volume.m3.[ms_list]
lw_elev=lakes$Volume.m3.[lw_list]
minnow_elev=lakes$Volume.m3.[minnow_list]


var.test(gl_ph, ms_ph,na.rm=T)
var(gl_ph,na.rm=T)

boxplot(gl_ph,at_ph, ms_ph,lw_ph, minnow_ph, names=c("gl", "at","ms","lw","min"))



data=data.frame(
  name=c(rep("Relict",length(gl_ph)),rep("Atlanic",length(at_ph)),rep("Mississippian",length(ms_ph)), rep("Lowland", length(lw_ph)),rep("Minnows", length(minnow_ph))),
  pH=c(gl_ph,at_ph, ms_ph,lw_ph, minnow_ph),elev=c(gl_elev,at_elev, ms_elev,lw_elev, minnow_elev),
  lat=c(lakes$lakes$SIO2..mg.L.1.[gl_list],lakes$lakes$SIO2..mg.L.1.[at_list],lakes$lakes$SIO2..mg.L.1.[ms_list],lakes$lakes$SIO2..mg.L.1.[lw_list],lakes$lakes$SIO2..mg.L.1.[minnow_list]),
  long=c(lakes$Ca..mg.L.1.[gl_list],lakes$Ca..mg.L.1.[at_list],lakes$Ca..mg.L.1.[ms_list],lakes$Ca..mg.L.1.[lw_list],lakes$Ca..mg.L.1.[minnow_list]))





data
ggplot(data, aes(x=name, y=elev, fill=name)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.2, alpha=0.5) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Elevation Ranges") +
    xlab("Species Groups")+ylab("Elevation (ft)")
  

```



```{r}

dat=data.frame()
dat = data.frame(
  species=c(rep("FHM",length(which(lakes$FHM>=1))),rep("NRD",length(which(lakes$NRD >=1))), rep("PD",length(which(lakes$PD >=1))), rep("LC",length(which(lakes$LC >=1))),rep("CC",length(which(lakes$CC >=1))),rep("CS",length(which(lakes$CS >=1))),rep("BND",length(which(lakes$BND >=1))), rep("GS",length(which(lakes$GS >=1)))),
  pH=c(lakes$LAB_pH[which(lakes$FHM >=1)],lakes$LAB_pH[which(lakes$NRD >=1)],lakes$LAB_pH[which(lakes$PD >=1)],lakes$LAB_pH[which(lakes$LC >=1)],lakes$LAB_pH[which(lakes$CC >=1)],lakes$LAB_pH[which(lakes$CS >=1)],lakes$LAB_pH[which(lakes$BND >=1)],lakes$LAB_pH[which(lakes$GS >=1)]),
  Lat=c(lakes$SIO2..mg.L.1.[which(lakes$FHM >=1)],lakes$SIO2..mg.L.1.[which(lakes$NRD >=1)],lakes$SIO2..mg.L.1.[which(lakes$PD >=1)],lakes$SIO2..mg.L.1.[which(lakes$LC >=1)],lakes$SIO2..mg.L.1.[which(lakes$CC >=1)],lakes$SIO2..mg.L.1.[which(lakes$CS >=1)],lakes$SIO2..mg.L.1.[which(lakes$BND >=1)],lakes$SIO2..mg.L.1.[which(lakes$GS >=1)]),
  Long=c(lakes$Ca..mg.L.1.[which(lakes$FHM >=1)],lakes$Ca..mg.L.1.[which(lakes$NRD >=1)],lakes$Ca..mg.L.1.[which(lakes$PD >=1)],lakes$Ca..mg.L.1.[which(lakes$LC >=1)],lakes$Ca..mg.L.1.[which(lakes$CC >=1)],lakes$Ca..mg.L.1.[which(lakes$CS >=1)],lakes$Ca..mg.L.1.[which(lakes$BND >=1)],lakes$Ca..mg.L.1.[which(lakes$GS >=1)]),
  elev=c(lakes$Volume.m3.[which(lakes$FHM >=1)],lakes$Volume.m3.[which(lakes$NRD >=1)],lakes$Volume.m3.[which(lakes$PD >=1)],lakes$Volume.m3.[which(lakes$LC >=1)],lakes$Volume.m3.[which(lakes$CC >=1)],lakes$Volume.m3.[which(lakes$CS >=1)],lakes$Volume.m3.[which(lakes$BND >=1)],lakes$Volume.m3.[which(lakes$GS >=1)]),
  col=c(lakes$DOC..mg.L.1.[which(lakes$FHM >=1)],lakes$DOC..mg.L.1.[which(lakes$NRD >=1)],lakes$DOC..mg.L.1.[which(lakes$PD >=1)],lakes$DOC..mg.L.1.[which(lakes$LC >=1)],lakes$DOC..mg.L.1.[which(lakes$CC >=1)],lakes$DOC..mg.L.1.[which(lakes$CS >=1)],lakes$DOC..mg.L.1.[which(lakes$BND >=1)],lakes$DOC..mg.L.1.[which(lakes$GS >=1)]))



dookie=matrix(NA, 18,17)
for(i in 1:length(minnows)){
  for(j in 1:18){
    dookie[j,i]=mean(lakes[which(lakes[,(20+minnows[i])]>=1),j], na.rm=T)
  }
}

colnames(dookie)=species_list[minnows]
rownames(dookie)=colnames(lakes[c(1:18)])
dookie=t(dookie)
dookie=as.data.frame(dookie)
dookie$Groups=dist_groups
#dookie=dookie[,-c(17,18,19)]

minnow_pca=prcomp(dookie[,c(1:length(dookie[1,])-1)], center=T, scale=T)
minnow_pca=prcomp(dookie[,c(1,2,18)], center=T, scale=T)
plot(minnow_pca, type="l",main="")
ggbiplot(minnow_pca,ellipse=T,  obs.scale=1, var.scale=1, labels = rownames(dookie), groups=dookie[,length(dookie[1,])])
print(study_pca)


library(ggbiplot)
dat=na.omit(dat)
do = tsne(dat[,-1], perplexity=50)
plot(do, col=dat[,1])
try = prcomp(dat[,-1], center=T, scale=T)

ggbiplot(try,obs.scale=1, var.scale=1, groups=dat[,1]) + stat_ellipse()
trydo = tsne(try$rotation)
plot(trydo)
```
```{r}



cat=dookie[c(4,2,15,16,7,6,14,17),]

study_names=species_list[study]
cat =matrix(NA,5, 8)
for(i in 1:8){
  for(j in 2:6){
    cat[(j-1),i] = mean(dat[which(dat$species == study_names[i]),j], na.rm=T)
  }
}
colnames(cat)=study_names
rownames(cat)=c("pH","Lat","Long","elev","col")

cat=t(cat)
cat=as.data.frame(cat)
cat$Group = c("AT","MS","MS","LW","GL","GL","GL","GL")
cat=cbind(cat, Group)

study_pca=prcomp(cat[,c(1:length(cat[1,])-1)], center=T, scale=T)
plot(study_pca, type="l",main="")
ggbiplot(study_pca,ellipse=T,  obs.scale=1, var.scale=1, labels = rownames(cat), groups=cat[,length(cat[1,])])
print(study_pca)





boxplot(dat$pH~dat$species)
boxplot(dat$elev~dat$species)
boxplot(dat$Lat~dat$species)
boxplot(dat$Long~dat$species)
boxplot(dat$col~dat$species)
ggplot(dat, aes(x=Long, y = Lat, color=species))+ 
  stat_ellipse(level=.97, size=1.2) +xlab("Longitude") + ylab("Latitude")+labs("Species Group") + ggtitle("Geographic Distribution")


```
```{r}

# trying to make a correlation matrix of alsc variables

mydata=lakes[,c(1:19)]
cormat=round(cor(mydata,use="pairwise.complete.obs"),2)

melted_cormat <- melt(cormat)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + geom_tile() +theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1))

cormat
```


```{r}


mi=presabs[,minnows]
di = presabs[,minnows]
study=presabs[,c(12,38,32,30,10,9,24,8)]

mi_vec2=vector()
for(i in 1:length(mi[1,])){
  mi_vec2[i]=sum(mi[,i])
}
mi=mi[,which(mi_vec2 > 2)]

study_vec=vector()
for(i in 1:length(study[,1])){
  study_vec[i]=sum(study[i,])
}

study=study[which(study_vec != 0),]
mi=mi[which(mi_vec != 0),]
#mi=sample(c(1:length(mi[,1])), size=100, replace=F)
studynmds=metaMDS(study[sample(1:length(study[,1]),600, replace=F),], k=3,try = 25)




```


```{r}
colnames(mi)=species_list[minnows]
mi=t(mi)
plot(nestednodf(mi),names=T)

mi_nat=mi[-c(3,5,16),]
mi_vecnat=vector()
for(i in 1:length(mi_nat[1,])){
  mi_vecnat[i]=sum(mi_nat[,i])
}


mi_nat=mi_nat[,which(mi_vecnat != 0)]
plot(nestednodf(mi_nat), names=T)

glacial_nest=mi[c(6,7,8,11,10,14,17),]

mi_vecgla=vector()
for(i in 1:length(glacial_nest[1,])){
  mi_vecgla[i]=sum(glacial_nest[,i])
}
glacial_nest=glacial_nest[, which(mi_vecgla != 0)]
plot(nestedtemp(glacial_nest))
plot(nestednodf(glacial_nest), names=T, col="#D4D45F")


## Mississippian 
ms_nest=mi[c(2,15),]

mi_vecms=vector()
for(i in 1:length(ms_nest[1,])){
  mi_vecms[i]=sum(ms_nest[,i])
}
ms_nest=ms_nest[, which(mi_vecms != 0)]

plot(nestednodf(ms_nest), names=T, col="#9FCB59")

#Atlantic
at_nest=mi[c(1,4,9),]

mi_vecat=vector()
for(i in 1:length(at_nest[1,])){
  mi_vecat[i]=sum(at_nest[,i])
}
at_nest=at_nest[, which(mi_vecat!= 0)]

plot(nestednodf(at_nest), names=T, col="#A08EAB")

#Lowland

lw_nest=mi[c(13,5,3,12,16),]

mi_veclw=vector()
for(i in 1:length(lw_nest[1,])){
  mi_veclw[i]=sum(lw_nest[,i])
}
lw_nest=lw_nest[, which(mi_veclw!= 0)]

plot(nestednodf(lw_nest), names=T, col="#769BBE")



```
```{r}
g = matrix(0, 4, length(mi[1,]))
rownames(g)=c("Lowland","Atlantic","Mississippian","Glacial")
for(i in 1:length(g[1,])){
  for(h in c(13,5,10,12,16)){
    if(mi[h,i] != 0){
      g[1,i]=1
    } else{NULL}
  }
  for(j in c(c(1,4,9))){
    if(mi[j,i] != 0){
      g[2,i]=1
    } else{NULL}
  }
  for(k in c(2,15)){
    if(mi[k,i] != 0){
      g[3,i]=1
    } else{NULL}
  }
  for(l in c(6,7,8,11,3,14,17)){
    if(mi[l,i] != 0){
      g[4,i]=1
    } else{NULL}
  }
}
par(mar = c(0, 6, .1, 0))
plot(nestednodf(g), names=T, col="#BE8776")
n=t(g)
n=as.data.frame(n)
v=vector()
for(i in 1:length(n[,1])){
  v[i]=sum(n[i,])
}

l=sample(c(1:800), 400, replace=F)
nm=metaMDS(n[l,], k=2)

ordiplot(nm, type="n", ylim=c(-.6,1), xlim=c(-1.3,1.3))
orditorp(nm,display="species",col="black",air=0.01,cex=1)

```



```{r}
di = presabs[,minnows]
di=t(di)
d = matrix(0, 4, length(di[1,]))
rownames(d)=c("Lowland","Atlantic","Mississippian","Glacial")
for(i in 1:length(d[1,])){
  for(h in c(13,5,10,12,16)){
    if(di[h,i] != 0){
      d[1,i]=1
    } else{NULL}
  }
  for(j in c(c(1,4,9))){
    if(di[j,i] != 0){
      d[2,i]=1
    } else{NULL}
  }
  for(k in c(2,15)){
    if(di[k,i] != 0){
      d[3,i]=1
    } else{NULL}
  }
  for(l in c(6,7,8,11,3,14,17)){
    if(di[l,i] != 0){
      d[4,i]=1
    } else{NULL}
  }
}
d=t(d)
ugh = matrix(0, 1116, 1)

for(i in 1:length(di[1,])){
  if((d[i,1]==1)&(d[i,2]==0)&(d[i,3] == 0) & (d[i,4]==0)){
    ugh[i,1]="Lowland Only"}
  if((d[i,1]==1)&(d[i,2]==1)&(d[i,3] == 0) & (d[i,4]==0)){
    ugh[i,1]="LW/AT"}
  if((d[i,1]==1)&(d[i,2]==1)&(d[i,3] == 1) & (d[i,4]==0)){
    ugh[i,1]="LW/AT/MS"}
  if((d[i,1]==1)&(d[i,2]==1)&(d[i,3] == 1) & (d[i,4]==1)){
    ugh[i,1]="All"}
  if((d[i,1]==1)&(d[i,2]==0)&(d[i,3] == 1) & (d[i,4]==0)){
    ugh[i,1]="LW/MS"}
  if((d[i,1]==1)&(d[i,2]==0)&(d[i,3] == 0) & (d[i,4]==1)){
    ugh[i,1]="LW/GL"}
  if((d[i,1]==1)&(d[i,2]==1)&(d[i,3] == 0) & (d[i,4]==1)){
    ugh[i,1]="LW/GL/AT"}
  if((d[i,1]==0)&(d[i,2]==1)&(d[i,3] == 0) & (d[i,4]==1)){
    ugh[i,1]="GL/AT"}
  if((d[i,1]==0)&(d[i,2]==0)&(d[i,3] == 0) & (d[i,4]==1)){
    ugh[i,1]="Glacial Only"}
  if((d[i,1]==0)&(d[i,2]==0)&(d[i,3] == 1) & (d[i,4]==1)){
    ugh[i,1]="GL/MS"}
  if((d[i,1]==0)&(d[i,2]==1)&(d[i,3] == 1) & (d[i,4]==1)){
    ugh[i,1]="GL/MS/AT"}
  if((d[i,1]==1)&(d[i,2]==0)&(d[i,3] == 1) & (d[i,4]==1)){
    ugh[i,1]="GL/MS/LW"}
  if((d[i,1]==0)&(d[i,2]==0)&(d[i,3] == 1) & (d[i,4]==0)){
    ugh[i,1]="Mississippi Only"}
  if((d[i,1]==0)&(d[i,2]==1)&(d[i,3] == 1) & (d[i,4]==0)){
    ugh[i,1]="MS/AT"}
  if((d[i,1]==0) & (d[i,2]==0) & (d[i,3] == 0) & (d[i,4]==0)){
    ugh[i,1]="None"}
}

```
```{r}
# creates matrix with lake groups and chemistry
dim(lakes)
toot=lakes[,c(1:beg-1)]
toot$zoop = ugh[,1]



# trying to get means for the pca 
mean_groups=matrix(NA, beg-1, 17)
uni = unique(toot$zoop)
for(i in 1:beg-1){
  for(j in 1:16){
    mean_groups[i,j]=mean(toot[which(toot$zoop == uni[j]),i], na.rm=T)
  }
}

st_lakes=lakes[which(lakes$ST != 0),]
for(i in 1:16){
  mean_groups[i,17]=mean(st_lakes[,i],na.rm=T)
}


colnames(mean_groups)=c(uni, "ST")
rownames(mean_groups)=c(colnames(toot[,c(1:beg-1)]))

mean_groups=t(mean_groups)


dookie=matrix(NA, 18,17)
for(i in 1:length(minnows)){
  for(j in 1:18){
    dookie[j,i]=mean(lakes[which(lakes[,(20+minnows[i])]>=1),j], na.rm=T)
  }
}





std_dev <- moo$sdev

#compute variance
pr_var <- std_dev^2
prop_varex <- pr_var/sum(pr_var)

plot(prop_varex, xlab = "Principal Component",
             ylab = "Proportion of Variance Explained",
             type = "b")

plot(cumsum(prop_varex), xlab = "Principal Component",
              ylab = "Cumulative Proportion of Variance Explained",
              type = "b")



lalo.pca=prcomp(pcavars[,(c(9,8,21,7,1,3,11,18,19,23,26,31,35))], center=T, scale=T)
plot(lalo.pca, type="l",main="")
ggbiplot(lalo.pca,ellipse=T,  obs.scale=1, var.scale=1, groups =pcavars[,length(pcavars[1,])])
print(lalo.pca)



count=vector()
for(i in 1:length(uni)){
  count[i] = length(which(toot$zoop==uni[i]))
}
count2 = which(count > 20)

# These are the geographical components: c(14,16,15,1,2)
# I took out glms = 5
# select groups mostly onlys c(2,7,8,3,5)
# 14 and 15 make the best for just the select group
moo=prcomp(mean_groups[c(2,7,8,3,5,17),c(1,2,14,15)], center=T, scale=T)

plot(moo, type="l")
abline(h=.01, col=2)
ggbiplot(moo, ellipse=T,obs.scale=1, var.scale=1, labels=rownames(mean_groups)[c(2,7,8,3,5,17)]) + ylim(-5,5) + xlim(-5,5)
barchart(toot$zoop)
moo

## Biggest components seem to be DOC, SI02, and Lab pH 6 DIC, 10Ca,,12 iron ,3 SO4
chem = prcomp(mean_groups[c(count2,17),-c(14,16,15,1,2,4,8,11,5,12,3)], center =T, scale=T)

plot(chem, type="l")
abline(h=.00, col=2)
chem
ggbiplot(chem, ellipse=T,obs.scale=1, var.scale=1, labels=rownames(mean_groups)[c(count2,17)]) + ylim(-2.8,2.5) + xlim(-3.5,3.5)

chem_mat = as.data.frame(chem$rotation)
tsn=tsne(mean_groups[c(count2,17),-c(14,16,15,1,2,4,8,11,5,12,3)])
plot(tsn, labels=T)
tsn=as.data.frame(tsn)
colnames(tsn)=colnames(chem)

install.packages("tsne")
library(tsne)

barchart(toot$zoop, col=1, main = "Frequency of Association Occurance")
ggplot(data=toot, aes(x=zoop)) +
  geom_bar(stat="identity")
plot(mean_groups[,2])
text(mean_groups[,2],labels = rownames(mean_groups))

boxplot(toot$SIO2..mg.L.1.~toot$zoop, las=2)




## combining physical and chemica 
both = prcomp(mean_groups[count2, -c(1,2,16,4,8,11,5,12,3,7)], center=T, scale=T)
plot(both, type="l")
both
ggbiplot(both, ellipse=T,obs.scale=1, var.scale=1, labels=rownames(mean_groups)[count2]) + ylim(-2.8,2.5) + xlim(-5.5,3.5)

plot(lakes$community_richness~ lakes$SIO2..mg.L.1.)
summary(lm(lakes$community_richness~lakes$SIO2..mg.L.1.+lakes$LAB_pH))
```


```{r}
## 14 and 15 would be physical 
st_lakes=st_lakes[,c(0:16)]
st_lakes$name="st"

pd_lakes = lakes[which(lakes$PD != 0),c(0:16)]
pd_lakes$name = "pd"

nrd_lakes = lakes[which(lakes$NRD != 0),c(0:16)]
nrd_lakes$name = "nrd"

lc_lakes = lakes[which(lakes$LC != 0),c(0:16)]
lc_lakes$name = "lc"

brm_lakes = lakes[which(lakes$BRM != 0),c(0:16)]
brm_lakes$name = "BRM"

gs_lakes = lakes[which(lakes$GS != 0),c(0:16)]
gs_lakes$name = "gs"

lnd_lakes = lakes[which(lakes$LND != 0),c(0:16)]
lnd_lakes$name = "lnd"

fsd_lakes = lakes[which(lakes$FSD != 0),c(0:16)]
fsd_lakes$name = "fsd"

cs_lakes = lakes[which(lakes$CS != 0),c(0:16)]
cs_lakes$name = "cs"

cc_lakes = lakes[which(lakes$CC != 0),c(0:16)]
cc_lakes$name = "cc"



st_min=rbind(cc_lakes,st_lakes, pd_lakes,nrd_lakes,lc_lakes,brm_lakes, lnd_lakes, cs_lakes)
st_min=na.omit(st_min[,-c(1,2,16,4,8,11,5,12,3,7)])
st_explore=prcomp(st_min[,-length(st_min[1,])], center=T, scale=T)
ggbiplot(st_explore, ellipse=T,obs.scale=1, var.scale=1,groups = st_min$name) + ylim(-3.8,4.5) + xlim(-5.5,3.5)
st_explore
rownames(st_min)=st_min$name


studynmds=metaMDS(st_min[,-length(st_min[1,])], k=3,try = 25)



ordiplot(studynmds, type="n")
ordihull(studynmds,groups=st_min$name,draw="polygon",col="grey90",label=T)
orditorp(studynmds,display="species",col="red",air=0.01)


pres=t(cpresabs)
com= prcomp(cpresabs, center =T)
ggbiplot(com, ellipse=T,obs.scale=1, var.scale=1)# +ylim(-3,3)+xlim(2,5)
predict(com,newdata = pres)
com
ty = prcomp()
```


```{r}

boxplot(lakes$DIC..mg.L.1.[which(lakes$GS != 0)],lakes$DIC..mg.L.1.[which(lakes$GS != 1)])
t.test(lakes$DIC..mg.L.1.[which(lakes$GS != 0)],lakes$DIC..mg.L.1.[which(lakes$GS != 1)])

boxplot(lakes$DIC..mg.L.1.[which(lakes$BND != 0)],lakes$DIC..mg.L.1.[which(lakes$BDN != 1)])
t.test(lakes$DIC..mg.L.1.[which(lakes$BND != 0)],lakes$DIC..mg.L.1.[which(lakes$BND != 1)])


boxplot(lakes$DIC..mg.L.1.[which(lakes$NRD != 0)],lakes$DIC..mg.L.1.[which(lakes$NRD != 1)])
t.test(lakes$DIC..mg.L.1.[which(lakes$NRD != 0)],lakes$DIC..mg.L.1.[which(lakes$NRD != 1)])


```

```{r}
pearl = lake$PD
for(i in 1:length(pearl)){
  if(){
    pearl[i]=0
  }else{NULL}
}

p = which(is.na(pearl))
pearl[p]=0

plot(pearl~ lake$SIO2..mg.L.1.)
abline(summary(lm(pearl~lake$SIO2..mg.L.1.)))






plot(lakes$community_richness, lakes$LAB_pH)
abline(lm(lakes$community_richness~lakes$LAB_pH+lakes$SIO2..mg.L.1.))
```


```{r}

## This will be nestedness analysis of 3 groups - clustered minnows, clustered predators, and those in the middle (no rare species)

tcpres=t(cpresabs)
mat=cbind(rownames(tcpres), c(1:length(tcpres[,1])))

t = matrix(0, 3, length(tcpres[1,]))
rownames(t)=c("ST&Min","Mix","IntPreds")
for(i in 1:length(t[1,])){
  for(h in c(1,31,9,29,22,11,27)){
    if(tcpres[h,i] != 0){
      t[1,i]=1
    } else{NULL}
  }
  for(j in c(2,3,4,5,8,10,12,13,14, 15, 16, 17, 23, 24,25,26,28,30,32,33,34,35)){
    if(tcpres[j,i] != 0){
      t[2,i]=1
    } else{NULL}
  }
  for(k in c(5,6,17,18,15,30,16)){
    if(tcpres[k,i] != 0){
      t[3,i]=1
    } else{NULL}
  }
}
plot(nestednodf(t), names=T, col="#BE8776")
mixst=t[c(1,2),]
mixst_vec=vector()
for(i in 1:length(mixst[1,])){
  mixst_vec[i]=sum(mixst[,i])
}
mixst=mixst[, which(mixst_vec != 0)]

mixst=t[c(3,2),]
mixst_vec=vector()
for(i in 1:length(mixst[1,])){
  mixst_vec[i]=sum(mixst[,i])
}
mixst=mixst[, which(mixst_vec != 0)]




plot(nestednodf(t[c(3,1),]),names=T)
plot(nestednodf(mixst), names=T,col="#BE8776")

st = presabs[,c(24,  9, 10,  8, 38, 32, 30, 12)]
st=t(st)
st_vec=vector()
for(i in 1:length(st[1,])){
  st_vec[i]=sum(st[,i])
}
st=st[, which(st_vec != 0)]
plot(nestednodf(st), names=T, col="#8ccfa8", cex=1)

```


```{r}
minnow_si = hist(lakes$SIO2..mg.L.1.[which(lakes$PS > 0)])$count

sipd = minnow_si /hist(lakes$SIO2..mg.L.1.)$counts[0:length(minnow_si)]

plot(sipd)

hist(lakes$community_richness)
boxplot(lakes$Volume.m3.~lakes$community_richness)

# Matters for PD, GS,NRD, CC, LND, LC, CLM, FF (young rely on plankton), RB, LMB, CCS, WS, BB, BT, PS
# Kinda matters for  
# Doesn't matter for BND, CS, MM, BRM, WE, LWF
# Opposite effect for BM 
```