---
title: "Untitled"
author: "Montana"
date: "6/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installing Library ------ 

```{r}

library(dplyr)
library(tidyr)
library(tidyverse)

```


# Defining Data Sheets ----- 

```{r}

fish = read.csv("FISH_MEASUREMENT_whole.csv")
sample = read.csv("FISH_SAMPLE.csv")
sites = read.csv("SITES.csv")

```

```{r}
all_data = filter_data(water = "LML", gear = "BEF", gear_code = "NAF", species = species)

CPUE.w.sec = CPUE_wide_seconds(all_data)



CPUE.w.shore = CPUE_wide_shore(all_data)








```

###### Plotting the CPUE data for all species from spring NAF boat electrofishing

```{r}
CPUE.l.sec = CPUE_long_seconds(all_data)

CPUE.l.sec %>%
  ggplot(aes(x = YEAR, y = (CPUE_seconds))) +
  geom_point() +
  geom_smooth(method = "lm") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +  
  facet_wrap(~SPECIES)
```

```{r}
CPUE.l.shore = CPUE_long_shore(all_data)

CPUE.l.shore %>%
  ggplot(aes(x = YEAR, y = (CPUE_shore))) +
  geom_point() +
  geom_smooth(method = "lm") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +  
  facet_wrap(~SPECIES)
```


```{r}
CPUE.l.shore %>%
  filter(SPECIES == "SMB") %>%
    ggplot(aes(x = YEAR, y = (CPUE_shore))) +
  geom_point() +
  geom_smooth(method = "lm") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```


