---
title: "Untitled"
author: "Montana"
date: "4/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)
```



```{r}
SIA_sample = read.csv("SI_SAMPLE.csv")
SIA_measurement = read.csv("SI_MEASUREMENT.csv")
SI = left_join(SIA_measurement, SIA_sample,"ISO_SAMP_N") %>%
  filter(WATER == "LML", CATEGORY %in% c("FISH","SNL","MUS"))


SI %>% 
  group_by(TAXA, YEAR, ISO_SAMP_N) %>%
  summarise(cat = n())

samp_2002 = SI %>%
  filter(YEAR == 2002) %>%
  group_by(TAXA) %>%
  summarise(cat = n())


## 2001 and 2002 seem to have the only useful data 

SI %>% 
  filter(YEAR == 2001) %>%
  ggplot(aes(x = D13C, y = D15N, col = TAXA),shape = c(1:10)) + geom_point() 

SI %>% 
  filter(YEAR %in% c(2001, 2002)) %>%
  ggplot(aes(x = D13C, y = D15N, col = TAXA)) + 
  geom_point(aes(shape = as.factor(YEAR))) + 
  stat_ellipse()


SI %>% 
  filter(YEAR %in% c(2001, 2002)) %>%
  ggplot(aes(x = D13C, y = D15N, col = TAXA, shape = as.factor(CATEGORY))) + 
  geom_point()+ 
  stat_ellipse(level = .9)

```

```{r, message=F}
LML = read.csv("JML.Data.Master.csv", header=T)

fish = read.csv("FISH_MEASUREMENT_whole.csv")

## species "mussel", "Phytoplankton"

LML %>% 
  filter(Species %in% c("SMB","CC","CS","MM","PS","SS")) %>%
  ggplot(aes(x = as.numeric(C), y = as.numeric(N), col = Species)) + 
  geom_point()+ 
  stat_ellipse(level = .9) + 
  ylab("d15N") + xlab("d13C") + 
  ggtitle("LML Isotopes Lepak 2001-2002")


LML %>% 
  
  ggplot(aes(x = as.numeric(C), y = as.numeric(N), col = Species)) + 
  geom_point()+ 
  stat_ellipse(level = .9) + 
  ylab("d15N") + xlab("d13C") + 
  ggtitle("LML Isotopes Lepak 2001-2002")

```

```{r}


LML = LML %>%
  filter(Group ==  "Fish") %>%
  group_by(Species) %>%
  filter(n() >= 3) 
  

LML_data = LML %>%
  data.frame(iso1 = as.numeric(.$C), 
             iso2 = as.numeric(.$N), 
             group = as.numeric(as.factor(.$Species)),
             community = rep(1, length(.$Species))) %>%
  select(iso1, iso2, group, community) %>%
  na.omit()

species_legend_LML = data.frame(Species = unique(LML$Species),
                            group = unique(LML_data$group)) 


legend  = species_legend_LML[order(species_legend_LML$group),]

LML_overlap = overlap(data_input = LML_data,comm = 1)


LML_overlap[order(LML_overlap[,1], decreasing = T),]

```



```{r}

cat = fish %>% select(LENGTH, WEIGHT, YSAMP_N, FISH_N)

LML_SMB = LML %>% filter(Species == "SMB") %>% na.omit()
  


LML_SMB %>% ggplot(aes(x = as.numeric(C), y = as.numeric(Length))) + 
  geom_point() + 
  geom_smooth(method = "lm")


LML_SMB %>% ggplot(aes(y = as.numeric(N), x = as.numeric(Length))) + 
  geom_point() + 
  geom_smooth(method = "lm")


LML_SMB %>% ggplot(aes(y = as.numeric(N),
                       x = as.numeric(C),
                       size = as.numeric(Length))) + 
  geom_point()

LML_SMB %>% ggplot(aes(y = Weight, x=as.numeric(Length)))+ geom_point()




cat = read.csv("FISH_AGE_GROWTH.csv") %>%
  select(FINAL_AGE, FISH_N)

dog = left_join(fish, cat, by = "FISH_N") %>%
  filter(FINAL_AGE != "", SPECIES == "SMB") %>%
  mutate(FINAL_AGE  = as.numeric(FINAL_AGE)) %>%
  select(LENGTH, FINAL_AGE)


unique(dog$FINAL_AGE)


dog %>% ggplot(aes(y = LENGTH, x = FINAL_AGE)) + 
  geom_point()

```
