---
title: "Untitled"
author: "Montana"
date: "4/14/2021"
output: ''
---

## Load in requirements ---

```{r, message = F}
# Libraries ----
library(easypackages)  
libraries("snow","plotrix", "SIBER","ggplot2", "tidyr","ellipse","mixtools",
          "mvtnorm","plot3D","scatterplot3d","scales","viridis","ggplot2",
          "gridExtra", "dplyr","RColorBrewer")

source("isotope_functions.R")

source("isotope_functions.R")

```


```{r, message=F, error = F}
## Load in data ------------
combined = read.csv("Data/SIA_Data.csv", header=T) %>%
  mutate(Sample.ID = as.numeric(Sample.ID)) %>% 
  left_join(read.csv("Data/ADKwebs_Data.csv"),.)
```
# Setup ---


```{r}
## Clean Setup for baesyain runs 
# TL has nas so if you na omit it causes issues
exclude =3
X=combined %>% 
  select(Sample.ID, d13C, d15N, Water, Species, Weight, Site) %>%
  group_by(Species, Water) %>%
  filter(n()>=exclude) %>%
  na.omit()

x = data.frame(iso1 = X$d13C,
               iso2 = X$d15N,
               group = as.numeric(as.factor(X$Species)),
               community = as.numeric(as.factor(X$Water))) 

species_legend = data.frame(Species = unique(X$Species),
                            group = unique(x$group)) 


legend  = species_legend[order(species_legend$group),]

lake = data.frame(Water = unique(X$Water), 
           Community = unique(x$community))

lake = lake[order(lake$Community),]
```



## Params ---
```{r}
x.p = seq(-38,-20,length.out=100); 
y.p = seq(0,9, length.out = 100) 
parms <- list();
parms$n.iter=2*10^4; 
parms$n.burnin=1*10^3; 
parms$n.thin=10
parms$n.chains=2     
priors=list();
priors$R=1*diag(2);
priors$k=2; 
priors$tau.mu=1.0E-3 # Vague priors 
Nsamples=1000
n.posts <- 50;
p.ell <- 0.90 # How much data to include? Standard ellipses --> p.ell = .9
n.points = 1000
```


## Color definition 
```{r}
spp=length(unique(x$group))
COLORS = c(brewer.pal(12, "Paired"),brewer.pal(8, "Set2"))
```


## Baeysian ellipses
 
```{r, error=F, message = F, warning = F}
COLORS = c(brewer.pal(12, "Paired"),brewer.pal(8, "Set2"))
COLORS = sample(COLORS, replace = FALSE, size = 18)
for(h in lake$Community){
  data = x %>% 
    filter(community == h, group != 11)
  #weight = X %>% 
   # filter(Water == lake$Water[h]) 
 # spp=length(unique(data$group))
  #siber.example <- createSiberObject(data) 
  #posterior <- siberMVN(siber.example, parms, priors)
  

  
  data = data[order(data$group),] %>% as.data.frame()
  
  


  spp=length(unique(data$group))
  
  color_scheme = COLORS[unique(data$group)]
  
  
  siber.example <- createSiberObject(data) 
 
  posterior <- siberMVN(siber.example, parms, priors)
  
  df = data.frame(color = color_scheme, group = unique(data$group))
  
  data = left_join(data, df)
  
  
  
  
  p = ggplot() +
    geom_point(data,
             mapping = aes(x = iso1, y= iso2, col = as.factor(group))) 
    ellip = array(0, dim=c((n.points),length(c(0,1)),spp))
  for(i in 1:spp){
    ellipse_data =  ellipse::ellipse(x = matrix(c(median(posterior[[i]][,1]),
                                  median(posterior[[i]][,2]),
                                  median(posterior[[i]][,3]),
                                  median(posterior[[i]][,4])),
                                2,2), 
                     centre = c(median(posterior[[i]][,5]),
                                median(posterior[[i]][,6])), level = .95, 
                     npoints = n.points)
    ellip[,,i] = ellipse_data
    if(i == 1){
      vector = vector()
      vector = rep(unique(data$group)[i], n.points)
    }else{
      new = rep(unique(data$group)[i], n.points)
      vector = c(vector,new )
    }
  }
  title = lake$Water[h]
  p = p + geom_point(aes(x = ellip[,1,], y = ellip[,2,], col = as.factor(vector)),size = 01, alpha = .09) +
    ggtitle(paste(title)) + 
    ylab("d15N") + xlab("d13C") + 
    scale_color_manual(values = unique(data$color), 
                       labels =legend[sort(unique(data$group)),1],
                       name = "Species"
                       )+ 
    theme(text = element_text(size = 13))
    #scale_color_discrete(name = "Species", labels = legend[sort(unique(data$group)),1])
  print(p)
}
```



```{r}
## Overlap Function --------------------

PRL_overlap = overlap(x,3,20)

LOP_overlap = overlap(x,2,20)


TPP_overlap = overlap(x,4,20)


overlap = full_join(as.data.frame(TPP_overlap),
                    as.data.frame(LOP_overlap)) %>%
  full_join(as.data.frame(PRL_overlap),.) %>%
  distinct(`Com 2`,`Com 4`, `Com 3`, .keep_all = T) %>%
  select('Spp Pair','Com 2',`Com 4`,`Com 3`)


overlap_csv = write.csv(overlap, "overlap.csv")
is.na(overlap)
mean(overlap[,1],na.rm=T)
overlap_richness = overlap  %>% 
  mutate_at(2:4,as.numeric)%>% 
  replace(. == 1, NA) %>%
  summarise_all(mean, na.rm=TRUE)
species_richness =  x %>% 
  group_by(community) %>% 
  summarise(Uni = n_distinct(group)) 
Lakes_overlap = cbind(t(overlap_richness[2:4]), species_richness$Uni[2:4]) %>% as.data.frame()


  


 
  
rbind(as.matrix(Lakes_overlap),as.matrix(HRM_overlap)) %>% as.data.frame() %>%
  ggplot(aes(x =.[,2], y = .[,1])) + geom_point()


species_richness

plot(species_richness$com)
```









##Investigating size 

```{r}
X %>% filter(Species == "CS") %>%
  ggplot(aes(y = as.numeric(TL) , x = d13C, col = Species)) +
    geom_point() + scale_y_continuous(trans='log2') + 
    geom_smooth(method= "lm", se = F) + 
    ylab("TL") + xlab("d13C") #+ 
  facet_wrap(~Water)

 X %>% filter(Species == "CS") %>% select(TL) 
  
combined %>% 
  filter(Species %in% c("CC","NRD")) %>%
  ggplot(aes(x = as.numeric(TL), y = d15N, col = Species)) +
  geom_point() + scale_x_continuous(trans='log2') +
  ylab("d15N") + xlab("TL") +
  geom_smooth(method= "lm", se = F) +
  facet_wrap(~Water)
  


cat = X %>% filter(Species == "CS")
summary(lm(cat$d13C ~ as.numeric(cat$TL)))
summary(lm(cat$d15N ~ as.numeric(cat$TL)))
plot(cat$d15N~ cat$TL)
abline(lm(cat$d15N ~ as.numeric(cat$TL)))


plot(cat$d13C , cat$TL)
abline(lm(as.numeric(cat$TL)~cat$d13C))


all_data %>% filter(SPECIES == "CS") %>%
  ggplot(aes(x = WEIGHT, y = LENGTH)) +
  geom_point()


all_data %>% filter(SPECIES == "CS") 
CS = all_data %>% filter(SPECIES == "CC") %>% select(WEIGHT, LENGTH)

hist(CS$LENGTH, xlim=c(170,230), ylim=c(0,10))




combined %>% 
  filter(Species %in% c("CC","NRD", "PS", "ST","GS","BND")) %>% 
  filter(Water != "LML" & Water != "HRM") %>%
  ggplot(aes(x = as.numeric(TL), y = d15N, col = Species)) +
  geom_point() + scale_x_continuous(trans='log2') +
  ylab("d15N") + xlab("TL") +
  geom_smooth(method= "lm", se = F) +
  ylim(5,10) + xlim(16,256) +
  facet_wrap(~Water)
```





```{r}
## Area Plots ----------------
group.ML <- groupMetricsML(siber.example)

SEA.B <- siberEllipses(posterior)

siberDensityPlot(SEA.B, xticklabels = colnames(group.ML), 
                xlab = c("Community | Group"),
                ylab = expression("Standard Ellipse Area " ('\u2030' ^2) ),
                bty = "L",
                las = 1,
                main = "SIBER ellipses on each group"
                )

# Add red x's for the ML estimated SEA-c
points(1:ncol(SEA.B), group.ML[3,], col="red", pch = "x", lwd = 2)


```



## Relative overlap in total area 
```{r}
## Relative overlap between ellipses 

siber.example <- createSiberObject(x) 
posterior <- siberMVN(siber.example, parms, priors)
mu.post <- extractPosteriorMeans(siber.example, posterior)
layman.B <- bayesianLayman(mu.post)




cat = data_setup(1)






## Heron Marsh 
for(h in 1:5){
  
  data = X  %>%
    data.frame(iso1 = .$d13C,
              iso2 = .$d15N,
              group = as.numeric(as.factor(.$Species)),
              community = as.numeric(as.factor(.$Site)))   %>% 
    filter(Water == "HRM", Site == h) %>%
    select(iso1, iso2, group, community) %>%
    group_by(group, community) %>%
    filter(n()>=exclude) %>%
    na.omit() 
  
  data = data[order(data$group),]
  
  data = as.data.frame(data)
  dat = data_setup(data,h,100)
  ellipse.area = siberEllipses(dat[[2]])
  TA = rowSums(ellipse.area)
  ellipse.area = ellipse.area/TA
  
  spec = names(dat[[2]]) %>%
    as.data.frame() %>%
    separate(1, into = c("com","sp"))
  names = legend$Species[as.numeric(spec$sp)]
  colnames(ellipse.area) = names
    vec = vector()
  for(i in 1:length(ellipse.area[1,])){
    cat= ellipse.area[ellipse.area[,i] >  quantile(x = ellipse.area[,i] ,probs = .05) &
               ellipse.area[,i] < quantile(x = ellipse.area[,i] ,probs = .95),i]
    vec = cbind(vec, cat)
  }
  colnames(vec)=names
  median_area = vec %>% as.data.frame() %>%
    summarise_all(list(median))
  p = vec %>%
    as.data.frame() %>%
    pivot_longer(1:length(names(dat[[2]])),
                 names_to = "SP",
                 values_to = "Dat") 
   g = ggplot() + 
    geom_point(p, mapping = aes(y = SP , x = Dat)) + xlim(0,1) + 
    ggtitle(paste("HRM Site",h)) +
    ylab("Species") + 
    xlab("Relative Niche Area") + 
    theme(text = element_text(size = 18)) +
    geom_point(mapping =aes(x = as.numeric(median_area[1,]), 
                            y = legend$Species[as.numeric(spec$sp)]),
               col = "red", pch = 2, size = 4)
  print(g)
}




```

```{r}
for(h in 2:4){
  dat = data_setup(x,h,11)

  ellipse.area = siberEllipses(dat[[2]])
  TA = rowSums(ellipse.area)
  ellipse.area = ellipse.area/TA
  spec = names(dat[[2]]) %>%
    as.data.frame() %>%
    separate(1, into = c("com","sp"))
  names = legend$Species[as.numeric(spec$sp)]
  colnames(ellipse.area) = names
  vec = vector()
  for(i in 1:length(ellipse.area[1,])){
    cat= ellipse.area[ellipse.area[,i] >  quantile(x = ellipse.area[,i] ,probs = .05) &
               ellipse.area[,i] < quantile(x = ellipse.area[,i] ,probs = .95),i]
    vec = cbind(vec, cat)
  }
  colnames(vec) = names
  p = vec %>%
    as.data.frame() %>%
    pivot_longer(1:length(names(dat[[2]])),names_to = "SP",values_to = "Dat") %>%
    ggplot(aes(y = SP , x = Dat)) + geom_point() + xlim(0,.7) + ggtitle(lake$Water[h]) +
    ylab("Species") + xlab("Relative Niche Area") + theme(text = element_text(size = 18))
  print(p)
}


```


```{r, error=F, message = F, warning = F}
n.posts = 1000

for(h in 2:4){
  
  d = data_setup(x,h,11)
  spp=length(names(d[[2]]))
  
  spec = names(d[[2]]) %>%
    as.data.frame() %>%
    separate(1, into = c("com","sp"))
  names = legend$Species[as.numeric(spec$sp)]
  
  
  ellip = array(0, dim=c(n.posts, 4, spp))
  blank_vec_C = vector()
  blank_vec_N = vector()
 

  
  ellip = ellip_data(spp, n.posts, d)
  
  vector = rep(names, each = n.posts)
   

  spp.c = vector()
  spp.n = vector()
  spp.post.n = vector()
  spp.post.c = vector()
  
  for(j in 1:n.posts){
  
    
    C_range = max(ellip[j,3,])- min(ellip[j,1,])
    N_range = max(ellip[j,4,]) - min(ellip[j,2,])
    
   
    
    for(i in 1:spp){
      
    spp.post.c[i] = (max(ellip[j,3,i])- min(ellip[j,1,i]))/C_range
    
    spp.post.n[i] = (max(ellip[j,4,i])- min(ellip[j,2,i]))/N_range
    
    }
    spp.c = rbind(spp.c, spp.post.c)
    spp.n = rbind(spp.n, spp.post.n)
  }
  
      
    for(i in 1:length(spp.c[1,])){
    SPP.C= spp.c[spp.c[,i] >  quantile(x = spp.c[,i] ,probs = .05) &
               spp.c[,i] < quantile(x = spp.c[,i] ,probs = .95),i]
    blank_vec_C = cbind(blank_vec_C, SPP.C)
    
    SPP.N= spp.n[spp.n[,i] >  quantile(x = spp.n[,i] ,probs = .05) &
               spp.n[,i] < quantile(x = spp.n[,i] ,probs = .95),i]
    blank_vec_N = cbind(blank_vec_N, SPP.N)
  }
  
  median_C = blank_vec_C %>% as.data.frame() %>%
    summarise_all(list(median))
  
   median_N = blank_vec_N %>% as.data.frame() %>%
    summarise_all(list(median))
  
  colnames(blank_vec_C)=legend$Species[as.numeric(spec$sp)]
  
  frame = blank_vec_C %>% as.data.frame() %>%
    pivot_longer(1:length(blank_vec_C[1,]),
                 names_to = "SP",
                 values_to = "Dat") 
   p = ggplot() + 
    geom_point(frame, mapping=aes(y = SP, x = Dat)) +
    xlim(0,1) + ggtitle(paste(lake$Water[h])) +
    ylab("Species") + 
    xlab("Proportion of C axis")+
    theme(text = element_text(size = 18)) +
      geom_point(mapping =aes(x = as.numeric(median_C[1,]), 
                              y = legend$Species[as.numeric(spec$sp)]),
                 col = "red", pch = 2, size = 4)

   
  
  colnames(blank_vec_N)=legend$Species[as.numeric(spec$sp)]
  frame = blank_vec_N %>% as.data.frame() %>%
    pivot_longer(1:length(blank_vec_C[1,]),
                 names_to = "SP",
                 values_to = "Dat")   
  g = ggplot() + 
    geom_point(frame, mapping=aes(y = SP, x = Dat)) + 
    geom_point()+ geom_point() +
    xlim(0,1) + ggtitle(paste(lake$Water[h])) +
    ylab("Species") + 
    xlab("Proportion of N axis")+
    theme(text = element_text(size = 18))+
      geom_point(mapping =aes(x = as.numeric(median_C[1,]), 
                              y = legend$Species[as.numeric(spec$sp)]),
                 col = "red", pch = 2, size = 4)

  print(p)
  print(g)

}




```



## Layman's metrics 

```{r}
data = x
data = data[order(data$group),] %>% as.data.frame()
siber.example <- createSiberObject(data)
posterior <- siberMVN(siber.example, parms, priors)

ellipse.area = siberEllipses(posterior)
  




layman.B[[1]][,"TA"]

siberDensityPlot(cbind(layman.B[[1]][,"TA"], layman.B[[2]][,"TA"],layman.B[[3]][,"TA"],layman.B[[4]][,"TA"]),
                xticklabels = lake$Water, 
                bty="L", ylim = c(0,20),
                las = 1,
                ylab = "TA - Convex Hull Area",
                xlab = "")


siberDensityPlot(cbind(layman.B[[1]][,"NND"], layman.B[[2]][,"NND"],layman.B[[3]][,"NND"],layman.B[[4]][,"NND"]),
                xticklabels = lake$Water, 
                bty="L", ylim = c(0,4),
                las = 1,
                ylab = "NND",
                xlab = "")


siberDensityPlot(cbind(layman.B[[1]][,"CD"], layman.B[[2]][,"CD"],layman.B[[3]][,"CD"],layman.B[[4]][,"CD"]),
                xticklabels = lake$Water, 
                bty="L", ylim = c(0,4),
                las = 1,
                ylab = "CD",
                xlab = "")


siberDensityPlot(cbind(layman.B[[1]][,"SDNND"], layman.B[[2]][,"SDNND"],layman.B[[3]][,"SDNND"],layman.B[[4]][,"SDNND"]),
                xticklabels = lake$Water, 
                bty="L", ylim = c(0,4),
                las = 1,
                ylab = "SDNND",
                xlab = "")

for(i in lake$Community){
  siberDensityPlot(layman.B[[i]], xticklabels = colnames(layman.B[[i]]), 
                bty="L", ylim = c(0,20))
  comm1.layman.ml <- laymanMetrics(siber.example$ML.mu[[i]][1,1,],
                                 siber.example$ML.mu[[i]][1,2,]
                                 )
  points(1:6, comm1.layman.ml$metrics, col = "red", pch = "x", lwd = 2)
}
```


## Splitting up Heron Marsh 
####### Double check which legend you are using
```{r} 
COLORS = c(brewer.pal(12, "Paired"),brewer.pal(8, "Set2"))

for(h in 1:5){
  
  data = X  %>%
    data.frame(iso1 = .$d13C,
              iso2 = .$d15N,
              group = as.numeric(as.factor(.$Species)),
              community = as.numeric(as.factor(.$Site)))   %>% 
    filter(Water == "HRM", Site == h) %>%
    select(iso1, iso2, group, community) %>%
    group_by(group, community) %>%
    filter(n()>=exclude) %>%
    na.omit() 
  
  data = data[order(data$group),]
  
  data = as.data.frame(data)


  spp=length(unique(data$group))
  
  color_scheme = COLORS[unique(data$group)]
  
  
  siber.example <- createSiberObject(data) 
 
  posterior <- siberMVN(siber.example, parms, priors)
  
  df = data.frame(color = color_scheme, group = unique(data$group))
  
  data = left_join(data, df)
  
  
  data=data[order(data$group),]
  
  

  
  p = ggplot() +
    geom_point(data,
            mapping = aes(x = iso1, y= iso2, color = as.factor(data$group))) +
    ylim(5,11) + xlim(-36,-26)
  
  
  
  
  ellip = array(0, dim=c((n.points),length(c(0,1)),spp))
    
  for(i in 1:spp){
    ellipse_data =  ellipse::ellipse(x = matrix(c(median(posterior[[i]][,1]),
                                  median(posterior[[i]][,2]),
                                  median(posterior[[i]][,3]),
                                  median(posterior[[i]][,4])),
                                2,2), 
                     centre = c(median(posterior[[i]][,5]),
                                median(posterior[[i]][,6])), level = .9, 
                     npoints = n.points)
    ellip[,,i] = ellipse_data
  }
  
  p = p + geom_point(aes(x = ellip[,1,], y = ellip[,2,],color = rep(as.factor(unique(data$group)),each = 1000)),size = 01, alpha = .09) +
    ggtitle(paste("Site", paste(h))) + 
    ylab("d15N") + xlab("d13C") +
   scale_color_manual(values = unique(data$color), 
                       labels =legend[sort(unique(data$group)),1],
                       name = "Species"
                       ) + 
    theme(text = element_text(size = 19))
    
  print(p)

}
    
    
 
```


```{r}
## Heron Marsh Overlap 

HRM_Data = X  %>%
    data.frame(iso1 = .$d13C,
              iso2 = .$d15N,
              group = as.numeric(as.factor(.$Species)),
              community = as.numeric(as.factor(.$Site)))   %>% 
    filter(Water == "HRM") %>%
    select(iso1, iso2, group, community) %>%
    group_by(group, community) %>%
    filter(n()>=exclude) %>%
    na.omit()

HRM_S1 = overlap(data_input = HRM_Data, comm = 1, 20)
HRM_S2 = overlap(data_input = HRM_Data, comm = 2, 20)
HRM_S3 = overlap(data_input = HRM_Data, comm = 3, 20)
HRM_S4 = overlap(data_input = HRM_Data, comm = 4, 20)
HRM_S5 = overlap(data_input = HRM_Data, comm = 5, 20)


overlap = full_join(HRM_S1, HRM_S2, by = "Spp Pair") %>%
  full_join(HRM_S3,., by = "Spp Pair") %>%
  full_join(HRM_S4,.,by = "Spp Pair") %>%
  full_join(HRM_S5,by = "Spp Pair") %>%
  distinct(`Com 1`, `Com 2`, `Com 3`, `Com 4` , `Com 5`, .keep_all = T) %>%
  select(`Spp Pair`, `Com 1`, `Com 2`, `Com 3`, `Com 4` , `Com 5`)

overlap_richness = overlap %>% mutate_at(2:6,as.numeric)%>% 
  replace(. == 1, NA) %>%
  summarise_all(mean, na.rm=TRUE)

data.frame(sp = t(overlap_richness[2:6]), rich = c(3,3,2,3,4)) %>% 
  ggplot(aes(x = rich, y = sp)) + geom_point()

species_richness =  HRM_Data %>% 
  group_by(community) %>% 
  summarise(Uni = n_distinct(group))


HRM_overlap = data.frame(sp = t(overlap_richness[2:6]), rich = c(3,3,2,3,4))

```




