```{r}
library(dplyr)
library(ggplot2)
x=read.csv("ADKwebs_Data.csv", header=T)
cyprinid= c("FHM","NRD","CC","GS","PD","CS","BM","BND")
x_cy = x[which(any(cyprinid == x$Species[1])== TRUE),]

boxplot(x$Weight~x$Species, ylim=c(0,100), las=2)
plot(x$Weight~x$TL, col = as.numeric(as.factor(x$Species)))
legend("topright", as.character(unique(x$Species)), lty = rep(1, length(unique(x$Species))), col = c(1:length(unique(x$Species))), cex=.75)
ps = x[which(x$Species == "PS"),]
cc = x[which(x$Species == "CC"),]
bb = x[which(x$Species == "BB"),]
plot(cc$Weight~cc$TL)
plot(ps$Weight~ps$TL)
plot(bb$Weight~bb$TL, pch = bb$Water)
x[which(x$TL >20),]



cyp = x[which(apply(x, 1, function(r) any(r %in% cyprinid))==TRUE),]
boxplot(cyp$Weight~cyp$Species)
plot(cyp$Weight[which(cyp$Species =="NRD")])
x$Species[2] %in% cyprinid




x %>% 
  ggplot(aes(x = Water, y = Weight)) + geom_boxplot() + 
  scale_y_continuous(trans='log2') +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, hjust=1)) +
  facet_wrap(~Species)

x %>% 
  filter(Water == "LITTLE MOOSE") %>%
  ggplot(aes(x = Species, y = Weight)) + 
  geom_boxplot() + 
  scale_y_continuous(trans='log2') +
  ggtitle("Little Moose Lake")+ 
  theme(text = element_text(size = 20))
```


```{r}
x %>% 
  filter(Water == "LITTLE MOOSE") %>%
  ggplot(aes(x = Species, y = Weight)) + 
  geom_boxplot() + 
  scale_y_continuous(trans='log2') +
  ggtitle("Little Moose Lake")+ 
  theme(text = element_text(size = 20))
x %>% 
  filter(Water == "PANTHER") %>%
  ggplot(aes(x = Species, y = Weight)) + 
  geom_boxplot() + 
  scale_y_continuous(trans='log2') +
  ggtitle("Panther Lake")+ 
  theme(text = element_text(size = 20))
x %>% 
  filter(Water == "LONG") %>%
  ggplot(aes(x = Species, y = Weight)) + 
  geom_boxplot() + 
  scale_y_continuous(trans='log2') +
  ggtitle("Long Pond")+ 
  theme(text = element_text(size = 20))
x %>% 
  filter(Water == "Tom Peck ") %>%
  ggplot(aes(x = Species, y = Weight)) + 
  geom_boxplot() + 
  scale_y_continuous(trans='log2') +
  ggtitle("Tom Peck Pond")+ 
  theme(text = element_text(size = 20))
x %>% 
  filter(Water == "HERON") %>%
  ggplot(aes(x = Species, y = Weight)) + 
  geom_boxplot() + 
  scale_y_continuous(trans='log2') +
  ggtitle("Heron Marsh")+ 
  theme(text = element_text(size = 20))
```

```{r}
cc = x %>% filter(Species == "CC") 

cc %>% filter(Wate == "PRL")

```


```{r}

spp.day.water = x %>% 
  select(Location, Species, Day.Pulled) %>%
  group_by(Location, Species, Day.Pulled) %>%
  count()

totals = x %>%
  select(Location, Species, Day.Pulled) %>%
  group_by(Location, Species) %>%
  count()

write.csv(totals, "S2020_Sample.csv")
write.csv(spp.day.water, "S2020_Samp.csv")

```





